# Generated by Django 5.2.4 on 2025-09-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0009_remove_enquiry_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_test_drive',
            old_name='user',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='user',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='book_test_drive',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
