# Generated by Django 5.2.4 on 2025-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0010_rename_user_book_test_drive_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_test_drive',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
