# Generated by Django 5.2.4 on 2025-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0011_alter_book_test_drive_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_test_drive',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
