# Generated by Django 5.2.4 on 2025-09-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btmapp', '0002_userregisteration_city_userregisteration_door_no_and_more'),
        ('carsapp', '0013_alter_enquiry_phone_alter_enquiry_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btmapp.userregisteration'),
        ),
    ]
