# Generated by Django 5.2.4 on 2025-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0014_alter_enquiry_phone_alter_enquiry_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
