# Generated by Django 5.2.4 on 2025-09-19 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btmapp', '0002_userregisteration_city_userregisteration_door_no_and_more'),
        ('carsapp', '0015_alter_enquiry_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='btmapp.userregisteration'),
            preserve_default=False,
        ),
    ]
