# Generated by Django 5.2.4 on 2025-09-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('petrol', 'PETROL'), ('diesel', 'DIESEL'), ('ev', 'EV')], max_length=100)),
                ('seat_capacity', models.CharField(choices=[('2', '2 Seater'), ('4', '4 Seater'), ('5', '5 Seater'), ('7', '7 Seater')], max_length=10)),
                ('transmission_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('total_km_driven', models.PositiveIntegerField()),
                ('bootspace', models.PositiveIntegerField(help_text='Bootspace in liters')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Rating out of 5.0', max_digits=2)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='rent_car_images/')),
            ],
        ),
    ]
