# Generated by Django 5.2.4 on 2025-09-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0007_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_test_drive',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
