# Generated by Django 5.2.4 on 2025-09-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0008_book_test_drive_phone_enquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
    ]
