# Generated by Django 6.0.1 on 2026-02-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcars', '0004_rename_miliege_to_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carz',
            name='category',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Minivan', 'Minivan'), ('Pickup Truck', 'Pickup Truck')], default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='carz',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carz',
            name='price_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carz',
            name='total_km_driven',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
